ヘッダーとヒーローの作成
Akidesign/frontend-basic-site pull request #1
Opened 2024-02-07 02:09 UTC by Akidesign

ヘッダーとヒーローの作成です。
レビューをお願いします。

2024-02-09 01:58 UTC, toma0705 commented
a href　を使って、ヘッダーをクリックすると作ったサイトが再度読み込まれるようにしてください。

2024-02-09 01:59 UTC, toma0705 commented
hero::afterのbackground-colorは--color-hero-overlayでお願いします。

2024-02-09 03:04 UTC, Akidesign commented
a hrefとbackgroundcolorについて修正しました

2024-02-09 17:06 UTC, toma0705 commented
考え方は合っていると思います！しかし""の中のURLが別のサイトになっている気がします。そのため、""の中を . にしてみてください。

2024-02-09 17:11 UTC, toma0705 commented
href="." は、現在のディレクトリにリンクするため、通常はページ自体へのリンクとして扱われます。ロゴやヘッダーをクリックするとホームページや現在のページへ戻るためによく使われます。

2024-02-09 17:21 UTC, toma0705 commented
細かい点の修正を追加します。
・ "GRAND"から“GRAND”
・選べる100のレッスンであなたもギターヒーローに　から　選べる1000のレッスンであなたもギターヒーローに
・.heroのpaddingをfigmaと少し異なってします。
以上の変更をお願いします。

2024-02-10 06:51 UTC, toma0705 requested changes
コメントしました。

2024-02-10 06:51 UTC, toma0705 commented on index.html
> +        href="https://shinonome.io/frontend-basic-2023-html-css-assignment-baseline/chapter2/"
"https://shinonome.io/frontend-basic-2023-html-css-assignment-baseline/chapter2/"→"."

2024-02-10 06:51 UTC, toma0705 commented on index.html
> +            選べる100のレッスンであなたもギターヒーローに
100→1000

2024-02-10 06:51 UTC, toma0705 commented on index.html
> +            <span class="hero-main-copy-accent"> "GRAND" </span>
"GRAND"→”GRAND”

2024-02-10 08:24 UTC, Akidesign commented
修正しました。
リンクの部分が出来ているか不安です。

2024-02-10 16:28 UTC, toma0705 commented
インデックスとは、下の写真のことでしょうか？
<img width="817" alt="スクリーンショット 2024-02-11 011312" src="https://github.com/Akidesign/frontend-basic-site/assets/137295156/fc213e8a-3581-4fad-a3d5-bc9c71b1bfa6">

2024-02-11 02:59 UTC, Akidesign commented
そうです。
ヘッダーをクリックするとそのようなものが出てきます。

2024-02-11 04:13 UTC, Akidesign commented
自分なりにいろいろと調べてやってみた結果、.ではなく#にしたらうまくいきました。
この方法は良くない方法ですか？

2024-02-11 09:07 UTC, toma0705 reviewed
こちら側で模範解答を見たところ"."になっていてそのサイトもロゴをクリックするとインデックスになっていました。
"＃"はページの一番上に遷移、""はページのリロードになるのですが、サイト制作課題の意図がよくわからなかったので２次レビュアーにお願いしたいと思います。
コードの修正が少なく、驚きました。この調子で頑張ってください！

2024-02-11 23:59 UTC, higashiji2000 approved these changes
LGTM！

2024-02-11 23:59 UTC, higashiji2000 commented on style.css
> +}
メディアクエリ外でルールセット間は空行を挟んでいるので、こちらも統一したほうが統一感はでるかと！

2024-02-12 00:08 UTC, higashiji2000 commented
> こちら側で模範解答を見たところ"."になっていてそのサイトもロゴをクリックするとインデックスになっていました。
"＃"はページの一番上に遷移、""はページのリロードになるのですが、サイト制作課題の意図がよくわからなかったので２次レビュアーにお願いしたいと思います。

`'.'` のようにhrefにディレクトリまでしか指定しない場合の挙動は、サーバーの設定によって異なるようです。
模範解答をデプロイしているGithubPagesのような一般的なサーバーではこの挙動は制限されているようですが、ローカル環境では何も制限していないので出ているようです。
参考：https://www.futomi.com/lecture/htaccess/dir.html#gsc.tab=0

ダミーのリンクとしては `#` が一般的なので、現状の実装のほうが適切だと思います。
模範解答を修正しておきます 🚃

2024-02-12 01:37 UTC, higashiji2000 commented
修正しました
https://github.com/shinonome-inc/frontend-basic-2023-html-css-assignment-baseline/pull/7

2024-02-12 05:52 UTC, merged