Aboutの作成・Coursesの作成
Akidesign/frontend-basic-site pull request #2
Opened 2024-02-13 07:32 UTC by Akidesign

ブランチ切る場所を間違えていたので、直すのが大変だった

2024-02-14 03:25 UTC, Akidesign commented
Bakingのdescriptionのところが、もっと見るとの余白が狭くなってしまいましたが、どのように直したらよいでしょうか？

2024-02-15 08:49 UTC, toma0705 requested changes
以上の変更をし、調整することでうまくいくと思います！

2024-02-15 08:49 UTC, toma0705 commented on style.css
> +  height: 150px;
FrontmanとBackingのimageのheightは異なるのでここではheightは指定しない方がよい。

2024-02-15 08:49 UTC, toma0705 commented on style.css
> +  height: 76px;
FrontmanとBackingのimageのheightは異なるのでここのheightも削除

2024-02-15 08:49 UTC, toma0705 commented on style.css
> +  height: 150px;
FrontmanとBackingのimageのheightは異なるのでheightを削除

2024-02-16 01:35 UTC, Akidesign commented
修正しました

2024-02-16 14:53 UTC, toma0705 requested changes
.hero　縦のpadding
.about-img 縦も横と同じように｜アスペクト比を維持
.container max-width
以上の点の確認をお願いします。

2024-02-16 14:53 UTC, toma0705 commented on style.css
> +  transition-duration: 0.3s;
Backing以外のheightは150pxにしたいのでmin-height:150px;を追加してみてください。
figmaではCourseのCardのheigtは全て150pxなのですが、Backingのheightを見てみると、paddingで40px、Gapで10px、descriptionで76px、もっと見るで23pxなので合計が150pxを超えてしまうのでこのようにしたいと思います。

2024-02-16 14:53 UTC, toma0705 commented on style.css
> +  flex-grow: 1;
font-sizeの指定をお願いします。

2024-02-17 09:01 UTC, Akidesign commented
修正しました

2024-02-17 11:41 UTC, toma0705 commented
.hero　縦のpadding
.about-img 縦も横と同じように｜アスペクト比を維持
.container max-width
以上の点figmaを確認しながら修正をお願いします。

2024-02-17 12:22 UTC, Akidesign commented
見落としていました。修正しました。

2024-02-17 12:52 UTC, toma0705 commented
いい感じだと思います！

2024-02-17 17:31 UTC, higashiji2000 requested changes
![image](https://github.com/Akidesign/frontend-basic-site/assets/83479175/a2b56939-6fa9-472a-86a0-703d42a2bf39)

モバイル端末の画面幅だと表示が乱れるようなので、修正をお願いします。

クラス名の付け方がわかりやすくてGoodです！

2024-02-17 17:31 UTC, higashiji2000 commented on style.css
> +  line-height: normal;
```suggestion
```
このあたりはデフォルト値なので消しても問題ないかと思います。
必要最低限の行数でかけるようになるとGoodです。

2024-02-19 06:02 UTC, Akidesign commented
修正しました。
ですが、表示が崩れた場合、何回かリロードしたら崩れない状態です。
出来ているかどうかが不安です。

2024-02-20 15:43 UTC, higashiji2000 approved these changes
LGTM ⭐

2024-02-20 15:44 UTC, higashiji2000 commented
> 表示が崩れた場合、何回かリロードするかページをいったん閉じてまた表示したら崩れない状態です。

これはおそらく単にリロードしてないから変更が反映されていないだけかと思われます。

この拡張機能を使うとセーブするたびにブラウザに反映されるので便利です。
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

2024-02-21 00:14 UTC, merged