Signup・Footerの作成
Akidesign/frontend-basic-site pull request #5
Opened 2024-02-21 01:25 UTC by Akidesign

2024-02-21 07:05 UTC, toma0705 requested changes
Signup・Footerはとてもよくできていると思います！
ですが、過去に修正したところが修正前になっている気がします。
恐らく、chapter2のクローンをchapter3で使っているのではないかなと思います。
マージしたあとのmainbranchからクローンすると、上手くいくと思います。

2024-02-21 08:45 UTC, Akidesign commented
マージしたあとのmainbranchからクローンするとというところが良く分かりません。
マージした後のコミットはsignup+coursesの作成しかないのでクローンがうまくいきません。
修正箇所は確認しましたが、マージしたものが使われているのでないと思います。

2024-02-22 02:08 UTC, toma0705 commented
すみません！クローンではなくPullでした。

2024-02-22 02:20 UTC, toma0705 commented
about imageのheightやcontainerのmax widthなどの変更が反映させていない気がします。
<img width="337" alt="スクリーンショット 2024-02-22 111902" src="https://github.com/Akidesign/frontend-basic-site/assets/137295156/6d04bd7e-1841-4377-aecd-126424b993ea">
<img width="323" alt="スクリーンショット 2024-02-22 111958" src="https://github.com/Akidesign/frontend-basic-site/assets/137295156/314b25ed-fdce-4fd7-82ed-448fc248577e">

2024-02-22 03:00 UTC, toma0705 commented
すみません！クローンではなくPullでした。
しかし確認したところchapter2の時点で変更が反映されていませんでした。なのでPullはうまくできていて、chapter2がおかしくなっているのではないかなと思います。

2024-02-22 03:10 UTC, toma0705 commented
chapter2で変更したことは少ないのでchapter3でもabout imageのheightとcontainerのmax widthを変更すればOKだと思います。

2024-02-22 13:21 UTC, Akidesign commented
about imageのheightとcontainerのmax widthをchapter2と同じになるように修正しました

2024-02-23 10:51 UTC, toma0705 commented
<img width="887" alt="スクリーンショット 2024-02-23 194619" src="https://github.com/Akidesign/frontend-basic-site/assets/137295156/0483fab8-6c92-478c-959b-85b19738d11e">
max-width:880pxでお願いします。
height:100%が反映させていない気がします。

2024-02-23 12:16 UTC, Akidesign commented
max-width:880px・height:100%に修正しました

2024-02-23 13:37 UTC, toma0705 commented
<img width="639" alt="スクリーンショット 2024-02-23 223251" src="https://github.com/Akidesign/frontend-basic-site/assets/137295156/7605a116-33c8-4197-907c-5ff86bf8733f">
about-imgにheight:100%の追加をお願いします。

2024-02-23 14:00 UTC, Akidesign commented
修正しましたが、位置は合っていますか？

2024-02-24 01:11 UTC, toma0705 commented
合っています！一次レビューOKです！

2024-02-26 16:37 UTC, Higashiji reviewed
![image](https://github.com/Akidesign/frontend-basic-site/assets/83479175/d3c16ffb-8509-4ab4-b97c-428961de4316)
特定の画面幅でfooterが崩れているので、修正をお願いします。

2024-02-26 16:40 UTC, higashiji2000 requested changes

2024-02-26 16:40 UTC, higashiji2000 commented on index.html
> +          <a href="#" class="button signup-button">
buttonのスタイルを共通化できているのがめっちゃいいなと思いました！

2024-02-26 16:40 UTC, higashiji2000 commented on style.css
> +  grid-template-columns: 250px 1fr;
grid使えてて素敵です

2024-02-27 11:07 UTC, Akidesign commented
footerのメディアクエリの部分を修正しました

2024-02-27 16:25 UTC, higashiji2000 approved these changes

2024-02-28 01:53 UTC, merged